config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :shifts
  resources :users
  resources :organisations
  resources :password_resets
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  patch '/switch_organisation', to: 'users#switch_organisation'
  post '/shifts/create', to: 'shifts#create'
  # post '/create', to: 'organisations#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :users
  has_many :shifts, through: :users
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  
  def index
    @organisations = Organisation.all
    @user = current_user
    @organisation = Organisation.new
  end

  def show 
    @organisation = Organisation.find(params[:id])
  end

  #create new organisation and automatically add current user to it
  def create
    @user = current_user
    @organisation = Organisation.new(organisation_params)
    @organisation.save
    @user.update(organisation_id: @organisation.id)
    redirect_to organisations_path
  end

  def edit
    @organisation = Organisation.find(params[:id])
    @user = current_user
  end

  def update
    @organisation = Organisation.find(params[:id])
    @organisation.update(organisation_params)
    redirect_to organisations_path
  end

  # delete organisation and reset users to default state, not belonging to any organisation
  def destroy
    @user = current_user
    @organisation = Organisation.find(params[:id])
      @organisation.destroy
      users = User.all.select{|user| user.organisation_id == params[:id].to_i}
      users.each do |user|
          user.update(organisation_id: nil)  
      end
    redirect_to organisations_path
  end

  private

  def organisation_params
    params.require(:organisation).permit(:name, :hourly_rate)
  end

  
end

app/helpers/organisations_helper.rb
module OrganisationsHelper

end

app/views/organisations/edit.html.erb
<div class="organisations">
    <h1><u><%= link_to 'Adnat', organisations_path %></u></h1>
    <span>Logged in as </span><b><%= @user.name %></b>
    <h2>Edit Organisation<h2>
    <%= form_for @organisation do |f|  %>
      <div>
          <%= f.label 'Name: '%>
          <%= f.text_field :name, required: true %><br>
      </div><br>
      <div>
          <%= f.label 'Hourly rate: '%>
          <%= f.text_field :hourly_rate, required: true %><br>
      </div><br>  
      <button type="submit">Update</button> 
    <% end %>
    <%= form_tag organisation_path(@organisation.id), method: "delete" do %>
      <%= submit_tag "Delete" %>
    <% end %>
</div>

app/views/organisations/index.html.erb
<div class="organisations">
      <h1><u>Adnat</u></h1>
      <span>Logged in as </span><b><%= @user.name %></b>
      <%= link_to "Log Out", logout_path, method: :delete %><br>


      <% if @user.organisation_id != nil %>
         <% org = @organisations.select{ |org| org.id == @user.organisation_id}[0] %>
         <h2><%= org.name %></h2>
         <%= link_to 'View Shifts', shifts_path %>&nbsp&nbsp<%= link_to 'Edit', edit_organisation_path(id: org.id) %>&nbsp&nbsp <%= link_to 'Leave', switch_organisation_path(organisation_id: nil), method: "patch" %>
      <% else %>
      
      <p>You are not a member of any organisation. Join an existing one or create a new one<p><br>
      <h2>Organisations</h2>
         <ul><% @organisations.each do |org| %></ul>
            <li><%= org.name %>&nbsp
            <%= link_to "Edit", edit_organisation_path(id: org.id), permitted: true %>&nbsp
                  <%= link_to 'Join', switch_organisation_path(organisation_id: org.id), method: "patch" %>
            </li>
            
            
         <% end %>
         <h2>Create organisation</h2>
         <%= form_for @organisation do |f|  %>
            <div>
               <%= f.label 'Name: '%>
               <%= f.text_field :name, required: true %><br>
            </div><br>
            <div>
               <%= f.label 'Hourly rate: '%>
               <%= f.text_field :hourly_rate, required: true %><br>
            </div><br>  
            <button type="submit">Create and Join</button> 
            <% end %>
      <% end %>
</div>

  

app/views/organisations/show.html.erb
<h1><u><%= link_to 'Adnat', organisations_path %></u></h1>
<span>Logged in as </span>
<%= link_to "Log Out", root_path %><br>
<h2><%= @organisation.name %></h2><br>