config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :shifts
  resources :users
  resources :organisations
  resources :password_resets
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  patch '/switch_organisation', to: 'users#switch_organisation'
  post '/shifts/create', to: 'shifts#create'
  # post '/create', to: 'organisations#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :shifts
  validates_presence_of :name, :email, :password, :on => :create
  
  def send_password_reset
    UserMailer.password_reset(self).deliver
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      cookies[:user_id] = @user.id
      redirect_to organisations_path
    else
      flash[:message] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end
  
  def edit
    find_user
  end

  def update
    find_user
    if @user.update(user_params)
      flash[:message] = "Your account has been successfully updated."
      redirect_to organisations_path
    else
      
      render :edit
    end
  end

  #joining or leaving an organisation by current user
  def switch_organisation
    @user = current_user
    @user.shifts.destroy_all
    @user.update(organisation_id: params[:organisation_id])
    redirect_to organisations_path
  end
  
  
  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:organisation_id, :name, :password, :password_confirmation, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="users">
    <h1><u>Adnat</u></h1>

<%- # creating new user form -%>
    <h2>Sign up</h2>
        <%= form_for @user do |f| %>
          <div>
            <%= f.label 'Name: '%>
            <%= f.text_field :name, required: true %><br>
          </div><br>
          <div>
            <%= f.label 'Email: '%>
            <%= f.email_field :email, required: true %><br>
          </div><br>
          <div>
            <%= f.label 'Password'%><br>
            <%= f.label '(6 characters minimum)'%><br>
            <%= f.password_field :password, required: true, minlength: 6 %><br>
          </div><br>
          <div>
            <%= f.label 'Password confirmation '%><br>
            <%= f.password_field :password_confirmation, required: true %><br>
          </div><br>
          <button type="submit">Sign up</button>
        <% end %><br>
    <%= link_to "Log In", login_path %><br>
</div