config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :shifts
  resources :users
  resources :organisations
  resources :password_resets
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  patch '/switch_organisation', to: 'users#switch_organisation'
  post '/shifts/create', to: 'shifts#create'
  # post '/create', to: 'organisations#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :user

end

app/controllers/shifts_controller.rb
require 'pry'
require 'date'

class ShiftsController < ApplicationController
  
  def index
    @shift = Shift.new
    @user = current_user
    @users = User.all
    @shifts = Shift.all
  end

  def create
  
    # first validate user input 
    if validate_date(params[:date]) && validate_time(params[:start_time]) && validate_time(params[:finish_time])
  
    # second format params to match database
      @shift = Shift.new
      @shift[:user_id] = params[:user_id]
      arr = params[:date].split(/\D/)
      date_str = [arr[1], arr[0], arr[2]].join("-")
      start_str = params[:start_time]
      finish_str = params[:finish_time]
      @shift[:start] = DateTime.strptime(date_str + " " + start_str, '%d-%m-%Y %I:%M %p')
      @shift[:finish] = DateTime.strptime(date_str + " " + finish_str, '%d-%m-%Y %I:%M %p')
      @shift[:break_length] = params[:break_length]

  # persist data
      @shift.save
    end
    redirect_to shifts_path
  end

  private

  def shift_params
    params.require(:shift).permit(:user_id, :start, :finish, :break_length)
  end

end

app/helpers/shifts_helper.rb
module ShiftsHelper

#format dates

  def shift_date(shift)
    shift.start.strftime("%m/%d/%Y")
  end

  def shift_start(shift)
    shift.start.strftime("%I:%M %p")
  end

  def shift_finish(shift)
    shift.finish.strftime("%I:%M %p")
  end

  
# determine the shift's total worked hours
  def hours_worked(shift)
    start_time_minutes = shift.start.strftime("%H").to_i * 60 + shift.start.strftime("%M").to_i
    end_time_minutes = shift.finish.strftime("%H").to_i * 60 + shift.finish.strftime("%M").to_i
      if start_time_minutes > end_time_minutes
        total = 1440 - start_time_minutes + end_time_minutes - shift.break_length
      else
        total = end_time_minutes - start_time_minutes - shift.break_length
      end
    return (total/60.to_f).round(2)
  end

  def shift_cost(user, shift)
    Organisation.find_by_id(user.organisation_id).hourly_rate * hours_worked(shift)
  end

#filtering shifts based on current organisation
  def filter_shifts(current_user)
    shifts = []
      users = @users.select{|user| user.organisation_id == current_user.organisation_id}
      @shifts.each do |shift|
              users.each do |user|
                if user.id == shift.user_id
                  shifts.push(shift)
                end
              end
            end
          return shifts.reverse
   end


end

app/views/shifts/index.html.erb
<div class="shifts">
<h1><u><%= link_to 'Adnat', organisations_path %></u></h1>

<%- #displaying current user name and current organisation name -%>
<span>Logged in as <b><%= @user.name %></b>&nbsp&nbsp</span><%= link_to 'Log Out', logout_path, method: :delete %><br>
<h2><%= Organisation.find_by_id(@user.organisation_id).name %></h2>

<%- #displaying total shifts belonging to current organisation and the form for creating shift -%>
<h4>Shifts</h4>
<%= form_tag '/shifts/create' do %>
  <table style="width:90%">
  <tr>
    <th>Employee name</th>
    <th>Shift date</th> 
    <th>Start time</th>
    <th>Finish time</th>
    <th>Break length (minutes)</th>
    <th>Hours worked</th>
    <th>Shift cost</th>
  </tr>
  <% filter_shifts(@user).each do |shift| %>
    <tr style="width:90%">
       <td><%= User.find_by_id(shift.user_id).name %></td>
       <td><%= shift_date(shift) %></td>
       <td><%= shift_start(shift) %></td>
       <td><%= shift_finish(shift) %></td>
       <td><%= shift.break_length %></td>
       <td><%= hours_worked(shift) %></td>
       <td>$<%= shift_cost(@user, shift) %></td>
    </tr>
    <% end %>

          <tr><td><%= @user.name %></td>
                <%= hidden_field_tag 'user_id', @user.id %>
            <td><%= text_field_tag :date,nil, required: true %></td>
            <td><%= text_field_tag :start_time,nil, required: true %></td>
            <td><%= text_field_tag :finish_time,nil, required: true %></td>
            <td><%= number_field_tag :break_length, nil, required: true, within: 0...600  %></td>
            <td colspan="2"><%= submit_tag 'Create Shift' %></td> 
          </tr>
        </table>
    <% end %>
</div>
   